FROM alpine

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai

RUN apk add --no-cache alpine-conf ca-certificates su-exec && \
    /usr/sbin/setup-timezone -z Asia/Shanghai && \
    apk del alpine-conf && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /app

COPY build/docker/${TARGETPLATFORM}/octopus /app/octopus
COPY scripts/dockerfiles/entrypoint.sh /entrypoint.sh
COPY LICENSE THIRD_PARTY_NOTICES.md build/source/octopus-source.tar.gz /usr/share/doc/octopus/
COPY licenses /usr/share/doc/octopus/licenses/

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
